<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INBOOK_X2_PLUS" failures="1" tests="3" name="Test Runner-1" time="18.295" errors="0" timestamp="2025-03-14T17:19:22 IST">
  <testcase classname="com.camcast.HMS.patient.PatientBatchTest" name="createPatientAndAdmittTest" time="8.049"/>
  <testcase classname="com.camcast.HMS.patient.PatientBatchTest" name="patientInfoCheckTest" time="0.697"/>
  <testcase classname="com.camcast.HMS.patient.PatientBatchTest" name="patientOPDdocDetailsTest" time="2.23">
    <failure type="java.lang.AssertionError" message="expected [http://49.249.28.218:8081/AppServer/Health_Care_Hospital_System/admitdf.php?id=%2021] but found [http://49.249.28.218:8081/AppServer/Health_Care_Hospital_System/admitdf.php?id=%209]">
      <![CDATA[java.lang.AssertionError: expected [http://49.249.28.218:8081/AppServer/Health_Care_Hospital_System/admitdf.php?id=%2021] but found [http://49.249.28.218:8081/AppServer/Health_Care_Hospital_System/admitdf.php?id=%209]
at com.camcast.HMS.patient.PatientBatchTest.patientOPDdocDetailsTest(PatientBatchTest.java:107)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- patientOPDdocDetailsTest -->
</testsuite> <!-- Test Runner-1 -->
